vdebian:
  hosts:
    192.168.1.16:
      ansible_user: evere5t
    192.168.1.17:
      ansible_user: evere5t
    192.168.1.175:
      ansible_user: evere5t
    192.168.1.18:
      ansible_user: evere5t
load_balancer:
  hosts:
    192.168.1.16:
      ansible_user: evere5t
